development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:61d71c72345c8dae63cff1bfbe1ace02@sole.redistogo.com:9811/
  channel_prefix: blog_production
